# -*- coding: utf-8 -*-
"""
Generates problems_data.js from the SQLite database for GitHub Pages deployment.
Run: python generate_static_problems.py
"""

import json
import sys
import io
import db

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

counts = db.get_problem_counts()
all_data = {}

for topic_id in counts:
    problems = db.get_problems(topic_id)
    all_data[topic_id] = problems

js = "// Auto-generated by generate_static_problems.py — do not edit manually\n"
js += "const PROBLEMS_DATA = " + json.dumps(all_data, ensure_ascii=False, indent=2) + ";\n"

with open("problems_data.js", "w", encoding="utf-8") as f:
    f.write(js)

total = sum(len(v) for v in all_data.values())
print(f"Generated problems_data.js: {len(all_data)} topics, {total} problems")
