// Auto-generated by generate_static_problems.py — do not edit manually
const PROBLEMS_DATA = {
  "arith_prog": [
    {
      "id": 8,
      "topic_id": "arith_prog",
      "question": "a1 = 2, d = 3. Найди 5-й член прогрессии.",
      "type": "input",
      "answer": "14",
      "choices": null,
      "hint": "a5 = a1 + (5-1)*d = 2 + 4*3 = 14",
      "question_uz": "",
      "answer_uz": "",
      "choices_uz": "",
      "hint_uz": ""
    },
    {
      "id": 29,
      "topic_id": "arith_prog",
      "question": "Прогрессия: 2, 5, 8, 11, ... Разность d = ?",
      "type": "input",
      "answer": "3",
      "choices": null,
      "hint": "d = a₂ - a₁ = 5 - 2 = 3",
      "question_uz": "Progressiya: 2, 5, 8, 11, ... Farq d = ?",
      "answer_uz": "3",
      "choices_uz": "",
      "hint_uz": "d = a₂ - a₁ = 5 - 2 = 3"
    },
    {
      "id": 30,
      "topic_id": "arith_prog",
      "question": "a₁ = 3, d = 4. Найдите a₅.",
      "type": "input",
      "answer": "19",
      "choices": null,
      "hint": "aₙ = a₁ + (n-1)d = 3 + 4·4 = 19",
      "question_uz": "a₁ = 3, d = 4. a₅ ni toping.",
      "answer_uz": "19",
      "choices_uz": "",
      "hint_uz": "aₙ = a₁ + (n-1)d = 3 + 4·4 = 19"
    },
    {
      "id": 31,
      "topic_id": "arith_prog",
      "question": "Формула n-го члена арифметической прогрессии:",
      "type": "choice",
      "answer": "aₙ = a₁ + (n−1)d",
      "choices": [
        "aₙ = a₁ + (n−1)d",
        "aₙ = a₁ · dⁿ",
        "aₙ = a₁ · (n−1)",
        "aₙ = a₁ + nd"
      ],
      "hint": "Каждый следующий член отличается на d.",
      "question_uz": "Aritmetik progressiyaning n-chi elementi formulasi:",
      "answer_uz": "aₙ = a₁ + (n−1)d",
      "choices_uz": [
        "aₙ = a₁ + (n−1)d",
        "aₙ = a₁ · dⁿ",
        "aₙ = a₁ · (n−1)",
        "aₙ = a₁ + nd"
      ],
      "hint_uz": "Har bir keyingi inobat d ga farq qiladi."
    },
    {
      "id": 32,
      "topic_id": "arith_prog",
      "question": "Сумма первых 5 членов: 1, 3, 5, 7, 9. S₅ = ?",
      "type": "input",
      "answer": "25",
      "choices": null,
      "hint": "Sₙ = n(a₁ + aₙ)/2 = 5·(1+9)/2 = 25",
      "question_uz": "Birinchi 5 had: 1, 3, 5, 7, 9. S₅ = ?",
      "answer_uz": "25",
      "choices_uz": "",
      "hint_uz": "Sₙ = n(a₁ + aₙ)/2 = 5·(1+9)/2 = 25"
    },
    {
      "id": 33,
      "topic_id": "arith_prog",
      "question": "a₁ = 10, d = −2. Найдите a₄.",
      "type": "input",
      "answer": "4",
      "choices": null,
      "hint": "a₄ = 10 + (4-1)·(-2) = 10 - 6 = 4",
      "question_uz": "a₁ = 10, d = −2. a₄ ni toping.",
      "answer_uz": "4",
      "choices_uz": "",
      "hint_uz": "a₄ = 10 + (4-1)·(-2) = 10 - 6 = 4"
    }
  ],
  "circle": [
    {
      "id": 6,
      "topic_id": "circle",
      "question": "Радиус круга r = 5. Найди площадь (pi=3.14, округли до целых)",
      "type": "input",
      "answer": "78",
      "choices": null,
      "hint": "S = pi * r^2 = 3.14 * 25 = 78.5 ~ 78",
      "question_uz": "",
      "answer_uz": "",
      "choices_uz": "",
      "hint_uz": ""
    },
    {
      "id": 7,
      "topic_id": "circle",
      "question": "Длина окружности при r = 7 (pi=3.14, округли до целых)?",
      "type": "choice",
      "answer": "44",
      "choices": [
        "22",
        "44",
        "154",
        "49"
      ],
      "hint": "C = 2*pi*r = 2 * 3.14 * 7 = 43.96 ~ 44",
      "question_uz": "",
      "answer_uz": "",
      "choices_uz": "",
      "hint_uz": ""
    },
    {
      "id": 14,
      "topic_id": "circle",
      "question": "Радиус окружности равен 5. Найдите длину окружности (π ≈ 3.14).",
      "type": "input",
      "answer": "31.4",
      "choices": null,
      "hint": "C = 2πr = 2 · 3.14 · 5 = 31.4",
      "question_uz": "Aylananing radiusi 5. Aylana uzunligini toping (π ≈ 3.14).",
      "answer_uz": "31.4",
      "choices_uz": "",
      "hint_uz": "C = 2πr = 2 · 3.14 · 5 = 31.4"
    },
    {
      "id": 15,
      "topic_id": "circle",
      "question": "Диаметр круга равен 10. Найдите площадь (π ≈ 3.14).",
      "type": "input",
      "answer": "78.5",
      "choices": null,
      "hint": "r = 5; S = πr² = 3.14 · 25 = 78.5",
      "question_uz": "Doiraning diametri 10. Maydonini toping (π ≈ 3.14).",
      "answer_uz": "78.5",
      "choices_uz": "",
      "hint_uz": "r = 5; S = πr² = 3.14 · 25 = 78.5"
    },
    {
      "id": 16,
      "topic_id": "circle",
      "question": "Диаметр окружности d и радиус r связаны формулой:",
      "type": "choice",
      "answer": "d = 2r",
      "choices": [
        "d = 2r",
        "d = r/2",
        "d = r²",
        "d = πr"
      ],
      "hint": "Диаметр — отрезок через центр: d = 2r.",
      "question_uz": "Aylana diametri d va radiusi r qanday formula bilan bog‘langan?",
      "answer_uz": "d = 2r",
      "choices_uz": [
        "d = 2r",
        "d = r/2",
        "d = r²",
        "d = πr"
      ],
      "hint_uz": "Diametr — markaz orqali oʻtuvchi kesma: d = 2r."
    },
    {
      "id": 17,
      "topic_id": "circle",
      "question": "Длина окружности равна 62.8. Найдите радиус (π ≈ 3.14).",
      "type": "input",
      "answer": "10",
      "choices": null,
      "hint": "C = 2πr → r = C / (2π) = 62.8 / 6.28 = 10",
      "question_uz": "Aylana uzunligi 62.8. Radiusni toping (π ≈ 3.14).",
      "answer_uz": "10",
      "choices_uz": "",
      "hint_uz": "C = 2πr → r = C / (2π) = 62.8 / 6.28 = 10"
    },
    {
      "id": 18,
      "topic_id": "circle",
      "question": "Площадь круга равна 28.26. Найдите радиус (π ≈ 3.14).",
      "type": "input",
      "answer": "3",
      "choices": null,
      "hint": "S = πr² → r² = 28.26 / 3.14 = 9 → r = 3",
      "question_uz": "Doira yuzasi 28.26. Radiusni toping (π ≈ 3.14).",
      "answer_uz": "3",
      "choices_uz": "",
      "hint_uz": "S = πr² → r² = 28.26 / 3.14 = 9 → r = 3"
    }
  ],
  "complex_numbers": [
    {
      "id": 94,
      "topic_id": "complex_numbers",
      "question": "Мнимая единица i определяется как:",
      "type": "choice",
      "answer": "i² = -1",
      "choices": [
        "i² = -1",
        "i = -1",
        "i = √1",
        "i² = 1"
      ],
      "hint": "i = √(-1), поэтому i² = -1.",
      "question_uz": "Tasodifiy birlik i qanday aniqlanadi?",
      "answer_uz": "i² = -1",
      "choices_uz": [
        "i² = -1",
        "i = -1",
        "i = √1",
        "i² = 1"
      ],
      "hint_uz": "i = √(-1), shuning uchun i² = -1."
    },
    {
      "id": 95,
      "topic_id": "complex_numbers",
      "question": "Комплексное число z = 3 + 4i: вещественная часть равна:",
      "type": "choice",
      "answer": "3",
      "choices": [
        "3",
        "4",
        "4i",
        "7"
      ],
      "hint": "z = a + bi: Re(z) = a = 3, Im(z) = b = 4.",
      "question_uz": "z = 3 + 4i kompleks sonining haqiqiy qismi teng:",
      "answer_uz": "3",
      "choices_uz": [
        "3",
        "4",
        "4i",
        "7"
      ],
      "hint_uz": "z = a + bi: Re(z) = a = 3, Im(z) = b = 4."
    },
    {
      "id": 96,
      "topic_id": "complex_numbers",
      "question": "Модуль комплексного числа z = 3 + 4i равен |z| = ?",
      "type": "input",
      "answer": "5",
      "choices": null,
      "hint": "|z| = √(3² + 4²) = √(9 + 16) = √25 = 5.",
      "question_uz": "z = 3 + 4i kompleks sonining modulini toping: |z| = ?",
      "answer_uz": "5",
      "choices_uz": "",
      "hint_uz": "|z| = √(3² + 4²) = √(9 + 16) = √25 = 5."
    },
    {
      "id": 97,
      "topic_id": "complex_numbers",
      "question": "Комплексно сопряжённое к z = 2 + 5i:",
      "type": "choice",
      "answer": "2 - 5i",
      "choices": [
        "2 - 5i",
        "-2 + 5i",
        "-2 - 5i",
        "2 + 5i"
      ],
      "hint": "Сопряжённое z̄ = a - bi: меняем знак мнимой части.",
      "question_uz": "z = 2 + 5i orqali kompleks qo‘shni son:",
      "answer_uz": "2 - 5i",
      "choices_uz": [
        "2 - 5i",
        "-2 + 5i",
        "-2 - 5i",
        "2 + 5i"
      ],
      "hint_uz": "Qo‘shni z̄ = a - bi: tasodifiy qismini belgisini o‘zgartiramiz."
    },
    {
      "id": 98,
      "topic_id": "complex_numbers",
      "question": "Сумма (1 + 2i) + (3 - i) = ?",
      "type": "choice",
      "answer": "4 + i",
      "choices": [
        "4 + i",
        "4 + 3i",
        "2 + i",
        "4 - i"
      ],
      "hint": "Складываем вещественные и мнимые части: (1+3) + (2-1)i = 4 + i.",
      "question_uz": "(1 + 2i) + (3 - i) yig‘indisi = ?",
      "answer_uz": "4 + i",
      "choices_uz": [
        "4 + i",
        "4 + 3i",
        "2 + i",
        "4 - i"
      ],
      "hint_uz": "Haqiqiy va tasodifiy qismlarni qo‘shamiz: (1+3) + (2-1)i = 4 + i."
    }
  ],
  "derivative": [
    {
      "id": 104,
      "topic_id": "derivative",
      "question": "Производная f'(x) константы c = ?",
      "type": "choice",
      "answer": "0",
      "choices": [
        "0",
        "1",
        "c",
        "x"
      ],
      "hint": "Производная константы всегда 0: (c)' = 0.",
      "question_uz": "c konstantaning hosilasi f'(x) = ?",
      "answer_uz": "0",
      "choices_uz": [
        "0",
        "1",
        "c",
        "x"
      ],
      "hint_uz": "Konstantaning hosilasi har doim 0: (c)' = 0."
    },
    {
      "id": 105,
      "topic_id": "derivative",
      "question": "Производная функции f(x) = xⁿ равна:",
      "type": "choice",
      "answer": "n·xⁿ⁻¹",
      "choices": [
        "n·xⁿ⁻¹",
        "xⁿ⁺¹",
        "n·xⁿ",
        "(n-1)·xⁿ"
      ],
      "hint": "(xⁿ)' = n·xⁿ⁻¹ — степенное правило.",
      "question_uz": "f(x) = xⁿ funksiyaning hosilasi qanday?",
      "answer_uz": "n·xⁿ⁻¹",
      "choices_uz": [
        "n·xⁿ⁻¹",
        "xⁿ⁺¹",
        "n·xⁿ",
        "(n-1)·xⁿ"
      ],
      "hint_uz": "(xⁿ)' = n·xⁿ⁻¹ — daraja qoidasidir."
    },
    {
      "id": 106,
      "topic_id": "derivative",
      "question": "f(x) = 3x². Чему равна f'(x)?",
      "type": "choice",
      "answer": "6x",
      "choices": [
        "6x",
        "3x",
        "6x²",
        "x²"
      ],
      "hint": "(3x²)' = 3·2x = 6x.",
      "question_uz": "f(x) = 3x². f'(x) qancha?",
      "answer_uz": "6x",
      "choices_uz": [
        "6x",
        "3x",
        "6x²",
        "x²"
      ],
      "hint_uz": "(3x²)' = 3·2x = 6x."
    },
    {
      "id": 107,
      "topic_id": "derivative",
      "question": "Геометрический смысл производной f'(x₀) — это:",
      "type": "choice",
      "answer": "угловой коэффициент касательной",
      "choices": [
        "угловой коэффициент касательной",
        "площадь под графиком",
        "значение функции",
        "длина дуги"
      ],
      "hint": "f'(x₀) = tg α, где α — угол наклона касательной к оси Ox.",
      "question_uz": "f'(x₀) hosilasining geometrik ma'nosi nima?",
      "answer_uz": "to‘g‘ri chiziqning burchak koeffitsienti",
      "choices_uz": [
        "to‘g‘ri chiziqning burchak koeffitsienti",
        "grafik ostidagi maydon",
        "funksiya qiymati",
        "ark uzunligi"
      ],
      "hint_uz": "f'(x₀) = tg α, bu yerda α — to‘g‘ri chiziqning Oxga nisbatan burilish burchagi."
    },
    {
      "id": 108,
      "topic_id": "derivative",
      "question": "Производная функции f(x) = sin x:",
      "type": "choice",
      "answer": "cos x",
      "choices": [
        "cos x",
        "-cos x",
        "sin x",
        "-sin x"
      ],
      "hint": "(sin x)' = cos x.",
      "question_uz": "f(x) = sin x funksiyaning hosilasi qanday?",
      "answer_uz": "cos x",
      "choices_uz": [
        "cos x",
        "-cos x",
        "sin x",
        "-sin x"
      ],
      "hint_uz": "(sin x)' = cos x."
    }
  ],
  "geom_prog": [
    {
      "id": 64,
      "topic_id": "geom_prog",
      "question": "Прогрессия: 2, 6, 18, 54, ... Знаменатель q = ?",
      "type": "input",
      "answer": "3",
      "choices": null,
      "hint": "q = a₂ / a₁ = 6 / 2 = 3",
      "question_uz": "Progressiya: 2, 6, 18, 54, ... Qaysi q qiymati?",
      "answer_uz": "3",
      "choices_uz": "",
      "hint_uz": "q = a₂ / a₁ = 6 / 2 = 3"
    },
    {
      "id": 65,
      "topic_id": "geom_prog",
      "question": "a₁ = 5, q = 2. Найдите a₄.",
      "type": "input",
      "answer": "40",
      "choices": null,
      "hint": "aₙ = a₁ · q^(n-1) = 5 · 2³ = 40",
      "question_uz": "a₁ = 5, q = 2. a₄ ni toping.",
      "answer_uz": "40",
      "choices_uz": "",
      "hint_uz": "aₙ = a₁ · q^(n-1) = 5 · 2³ = 40"
    },
    {
      "id": 66,
      "topic_id": "geom_prog",
      "question": "Формула n-го члена геометрической прогрессии:",
      "type": "choice",
      "answer": "aₙ = a₁ · q^(n−1)",
      "choices": [
        "aₙ = a₁ · q^(n−1)",
        "aₙ = a₁ + q^n",
        "aₙ = a₁ · n",
        "aₙ = q^n"
      ],
      "hint": "Каждый член умножается на q: a₂=a₁q, a₃=a₁q², ...",
      "question_uz": "Geometrik progressiyaning n-chi had formulasi:",
      "answer_uz": "aₙ = a₁ · q^(n−1)",
      "choices_uz": [
        "aₙ = a₁ · q^(n−1)",
        "aₙ = a₁ + q^n",
        "aₙ = a₁ · n",
        "aₙ = q^n"
      ],
      "hint_uz": "Har bir had q ga ko‘paytiriladi: a₂=a₁q, a₃=a₁q², ..."
    },
    {
      "id": 67,
      "topic_id": "geom_prog",
      "question": "a₁ = 64, q = 0.5. Найдите a₃.",
      "type": "input",
      "answer": "16",
      "choices": null,
      "hint": "a₃ = 64 · (0.5)² = 64 · 0.25 = 16",
      "question_uz": "a₁ = 64, q = 0.5. a₃ ni toping.",
      "answer_uz": "16",
      "choices_uz": "",
      "hint_uz": "a₃ = 64 · (0.5)² = 64 · 0.25 = 16"
    },
    {
      "id": 68,
      "topic_id": "geom_prog",
      "question": "При |q| < 1 и бесконечном числе членов сумма прогрессии:",
      "type": "choice",
      "answer": "S = a₁ / (1 − q)",
      "choices": [
        "S = a₁ / (1 − q)",
        "S = a₁ · q",
        "S = ∞",
        "S = a₁ / q"
      ],
      "hint": "Формула бесконечной убывающей ГП: S = a₁ / (1 − q).",
      "question_uz": "|q| < 1 va cheksiz hadlar sonida progressiyaning yig‘indisi:",
      "answer_uz": "S = a₁ / (1 − q)",
      "choices_uz": [
        "S = a₁ / (1 − q)",
        "S = a₁ · q",
        "S = ∞",
        "S = a₁ / q"
      ],
      "hint_uz": "Cheksiz kamayuvchi GP formulası: S = a₁ / (1 − q)."
    }
  ],
  "integers": [
    {
      "id": 74,
      "topic_id": "integers",
      "question": "Какое из чисел является целым, но не натуральным?",
      "type": "choice",
      "answer": "-5",
      "choices": [
        "-5",
        "3",
        "1/2",
        "0.7"
      ],
      "hint": "Целые числа ℤ включают натуральные, 0 и отрицательные целые.",
      "question_uz": "Qaysi son butun, lekin natural emas?",
      "answer_uz": "-5",
      "choices_uz": [
        "-5",
        "3",
        "1/2",
        "0.7"
      ],
      "hint_uz": "Butun sonlar ℤ natural sonlar, 0 va manfiy butun sonlarni o‘z ichiga oladi."
    },
    {
      "id": 75,
      "topic_id": "integers",
      "question": "Множество ℤ содержит:",
      "type": "choice",
      "answer": "натуральные, 0 и отрицательные целые",
      "choices": [
        "натуральные, 0 и отрицательные целые",
        "только натуральные",
        "только отрицательные",
        "дроби"
      ],
      "hint": "ℤ = {..., -2, -1, 0, 1, 2, ...}.",
      "question_uz": "ℤ to‘plamida nima bor?",
      "answer_uz": "natural sonlar, 0 va manfiy butun sonlar",
      "choices_uz": [
        "natural sonlar, 0 va manfiy butun sonlar",
        "faqat natural",
        "faqat manfiy",
        "kasrlar"
      ],
      "hint_uz": "ℤ = {..., -2, -1, 0, 1, 2, ...}."
    },
    {
      "id": 76,
      "topic_id": "integers",
      "question": "Сумма (-7) + 7 = ?",
      "type": "input",
      "answer": "0",
      "choices": null,
      "hint": "Противоположные числа в сумме дают 0.",
      "question_uz": "(-7) + 7 yig‘indisi = ?",
      "answer_uz": "0",
      "choices_uz": "",
      "hint_uz": "Teskari sonlar yig‘indisi 0 ga teng."
    },
    {
      "id": 77,
      "topic_id": "integers",
      "question": "Верно ли: ℕ ⊂ ℤ (натуральные числа — подмножество целых)?",
      "type": "choice",
      "answer": "Да",
      "choices": [
        "Да",
        "Нет",
        "Частично",
        "Только при x > 0"
      ],
      "hint": "Любое натуральное число является целым, поэтому ℕ ⊂ ℤ.",
      "question_uz": "To‘g‘rimi: ℕ ⊂ ℤ (natural sonlar butun sonlarning qismi)?",
      "answer_uz": "Ha",
      "choices_uz": [
        "Ha",
        "Yo‘q",
        "Qisman",
        "Faqat x > 0 da"
      ],
      "hint_uz": "Har bir natural son butun son, shuning uchun ℕ ⊂ ℤ."
    },
    {
      "id": 78,
      "topic_id": "integers",
      "question": "Произведение (-3) × (-4) = ?",
      "type": "input",
      "answer": "12",
      "choices": null,
      "hint": "Минус на минус даёт плюс: (-3)×(-4) = 12.",
      "question_uz": "(-3) × (-4) ko‘paytmasi = ?",
      "answer_uz": "12",
      "choices_uz": "",
      "hint_uz": "Minusni minusga ko‘paytirish musbat beradi: (-3)×(-4) = 12."
    }
  ],
  "integral": [
    {
      "id": 109,
      "topic_id": "integral",
      "question": "∫xⁿ dx = ? (n ≠ -1)",
      "type": "choice",
      "answer": "xⁿ⁺¹/(n+1) + C",
      "choices": [
        "xⁿ⁺¹/(n+1) + C",
        "n·xⁿ⁻¹ + C",
        "xⁿ + C",
        "xⁿ/(n-1) + C"
      ],
      "hint": "Степень увеличивается на 1, делим на новую степень: ∫xⁿ dx = xⁿ⁺¹/(n+1) + C.",
      "question_uz": "∫xⁿ dx = ? (n ≠ -1)",
      "answer_uz": "xⁿ⁺¹/(n+1) + C",
      "choices_uz": [
        "xⁿ⁺¹/(n+1) + C",
        "n·xⁿ⁻¹ + C",
        "xⁿ + C",
        "xⁿ/(n-1) + C"
      ],
      "hint_uz": "Daraja 1 ga oshadi, yangi darajaga bo‘linadi: ∫xⁿ dx = xⁿ⁺¹/(n+1) + C."
    },
    {
      "id": 110,
      "topic_id": "integral",
      "question": "∫cos x dx = ?",
      "type": "choice",
      "answer": "sin x + C",
      "choices": [
        "sin x + C",
        "-sin x + C",
        "cos x + C",
        "-cos x + C"
      ],
      "hint": "Интеграл от косинуса — синус: ∫cos x dx = sin x + C.",
      "question_uz": "∫cos x dx = ?",
      "answer_uz": "sin x + C",
      "choices_uz": [
        "sin x + C",
        "-sin x + C",
        "cos x + C",
        "-cos x + C"
      ],
      "hint_uz": "Cosinusning integrali sin x + C ga teng."
    },
    {
      "id": 111,
      "topic_id": "integral",
      "question": "Геометрический смысл определённого интеграла ∫ₐᵇ f(x) dx:",
      "type": "choice",
      "answer": "площадь под кривой от a до b",
      "choices": [
        "площадь под кривой от a до b",
        "длина дуги",
        "объём тела",
        "наклон касательной"
      ],
      "hint": "Определённый интеграл вычисляет площадь криволинейной трапеции.",
      "question_uz": "Aniqlangan integral ∫ₐᵇ f(x) dx ning geometrik ma’nosi:",
      "answer_uz": "a dan b gacha egri ostidagi maydon",
      "choices_uz": [
        "a dan b gacha egri ostidagi maydon",
        "ark uzunligi",
        "jism hajmi",
        "to‘g‘ri chiziqning qiyaligi"
      ],
      "hint_uz": "Aniqlangan integral egri ostidagi trapetsiyaning maydonini hisoblaydi."
    },
    {
      "id": 112,
      "topic_id": "integral",
      "question": "Формула Ньютона–Лейбница: ∫ₐᵇ f(x) dx = ?",
      "type": "choice",
      "answer": "F(b) - F(a)",
      "choices": [
        "F(b) - F(a)",
        "F(a) + F(b)",
        "f(b) - f(a)",
        "F(b) + C"
      ],
      "hint": "F — первообразная f. ∫ₐᵇ f dx = F(b) - F(a).",
      "question_uz": "Nyuton–Leybnits formulasiga ko‘ra ∫ₐᵇ f(x) dx = ?",
      "answer_uz": "F(b) - F(a)",
      "choices_uz": [
        "F(b) - F(a)",
        "F(a) + F(b)",
        "f(b) - f(a)",
        "F(b) + C"
      ],
      "hint_uz": "F — f ning birinchi primitivi. ∫ₐᵇ f dx = F(b) - F(a)."
    },
    {
      "id": 113,
      "topic_id": "integral",
      "question": "∫ 1 dx = ?",
      "type": "choice",
      "answer": "x + C",
      "choices": [
        "x + C",
        "1 + C",
        "0",
        "C"
      ],
      "hint": "∫ 1 dx = ∫ x⁰ dx = x¹/1 + C = x + C.",
      "question_uz": "∫ 1 dx = ?",
      "answer_uz": "x + C",
      "choices_uz": [
        "x + C",
        "1 + C",
        "0",
        "C"
      ],
      "hint_uz": "∫ 1 dx = ∫ x⁰ dx = x¹/1 + C = x + C."
    }
  ],
  "irrationals": [
    {
      "id": 84,
      "topic_id": "irrationals",
      "question": "Какое из чисел является иррациональным?",
      "type": "choice",
      "answer": "√2",
      "choices": [
        "√2",
        "4/5",
        "0.5",
        "7"
      ],
      "hint": "√2 нельзя записать в виде p/q — это иррациональное число.",
      "question_uz": "Qaysi son irratsional?",
      "answer_uz": "√2",
      "choices_uz": [
        "√2",
        "4/5",
        "0.5",
        "7"
      ],
      "hint_uz": "√2 ni p/q tarzida yozib boʻlmaydi — bu irratsional sondir."
    },
    {
      "id": 85,
      "topic_id": "irrationals",
      "question": "Иррациональное число в десятичной форме:",
      "type": "choice",
      "answer": "бесконечная непериодическая дробь",
      "choices": [
        "бесконечная непериодическая дробь",
        "конечная дробь",
        "периодическая дробь",
        "целое число"
      ],
      "hint": "π = 3.14159... — бесконечна и непериодична.",
      "question_uz": "Irratsional son o‘nlik yozilishi:",
      "answer_uz": "cheksiz nodavriy kasr",
      "choices_uz": [
        "cheksiz nodavriy kasr",
        "cheklangan kasr",
        "davriy kasr",
        "butun son"
      ],
      "hint_uz": "π = 3.14159... — cheksiz va nodavriy."
    },
    {
      "id": 86,
      "topic_id": "irrationals",
      "question": "Число π ≈ 3.14159... является:",
      "type": "choice",
      "answer": "иррациональным",
      "choices": [
        "иррациональным",
        "рациональным",
        "натуральным",
        "целым"
      ],
      "hint": "π доказано трансцендентным и иррациональным числом.",
      "question_uz": "π ≈ 3.14159... soni qanday?",
      "answer_uz": "irratsional",
      "choices_uz": [
        "irratsional",
        "ratsional",
        "natural",
        "butun"
      ],
      "hint_uz": "π transsendental va irratsional son ekanligi isbotlangan."
    },
    {
      "id": 87,
      "topic_id": "irrationals",
      "question": "Сумма рационального и иррационального числа:",
      "type": "choice",
      "answer": "иррациональное",
      "choices": [
        "иррациональное",
        "рациональное",
        "натуральное",
        "зависит от чисел"
      ],
      "hint": "Если a ∈ ℚ и b ∉ ℚ, то a + b ∉ ℚ.",
      "question_uz": "Ratsional va irratsional son yig‘indisi:",
      "answer_uz": "irratsional",
      "choices_uz": [
        "irratsional",
        "ratsional",
        "natural",
        "sonlarga bog‘liq"
      ],
      "hint_uz": "Agar a ∈ ℚ va b ∉ ℚ bo‘lsa, a + b ∉ ℚ."
    },
    {
      "id": 88,
      "topic_id": "irrationals",
      "question": "Число e ≈ 2.718... (основание натурального логарифма) является:",
      "type": "choice",
      "answer": "иррациональным",
      "choices": [
        "иррациональным",
        "рациональным",
        "целым",
        "натуральным"
      ],
      "hint": "e — трансцендентное иррациональное число.",
      "question_uz": "e ≈ 2.718... (natural logarifm asosiy soni) qanday son?",
      "answer_uz": "irratsional",
      "choices_uz": [
        "irratsional",
        "ratsional",
        "butun",
        "natural"
      ],
      "hint_uz": "e — transsendental irratsional sondir."
    }
  ],
  "linear_eq": [
    {
      "id": 5,
      "topic_id": "linear_eq",
      "question": "Реши уравнение 3x + 9 = 0",
      "type": "input",
      "answer": "-3",
      "choices": null,
      "hint": "3x = -9  ->  x = -3",
      "question_uz": "",
      "answer_uz": "",
      "choices_uz": "",
      "hint_uz": ""
    },
    {
      "id": 19,
      "topic_id": "linear_eq",
      "question": "Решите уравнение: 2x + 6 = 0",
      "type": "input",
      "answer": "-3",
      "choices": null,
      "hint": "2x = -6 → x = -3",
      "question_uz": "Tenglamani yeching: 2x + 6 = 0",
      "answer_uz": "-3",
      "choices_uz": "",
      "hint_uz": "2x = -6 → x = -3"
    },
    {
      "id": 20,
      "topic_id": "linear_eq",
      "question": "Решите уравнение: 5x - 15 = 0",
      "type": "input",
      "answer": "3",
      "choices": null,
      "hint": "5x = 15 → x = 3",
      "question_uz": "Tenglamani yeching: 5x - 15 = 0",
      "answer_uz": "3",
      "choices_uz": "",
      "hint_uz": "5x = 15 → x = 3"
    },
    {
      "id": 21,
      "topic_id": "linear_eq",
      "question": "Уравнение 3x = 12 имеет решение:",
      "type": "choice",
      "answer": "x = 4",
      "choices": [
        "x = 4",
        "x = 3",
        "x = 9",
        "x = 36"
      ],
      "hint": "x = 12 / 3 = 4",
      "question_uz": "3x = 12 tenglamaning yechimi:",
      "answer_uz": "x = 4",
      "choices_uz": [
        "x = 4",
        "x = 3",
        "x = 9",
        "x = 36"
      ],
      "hint_uz": "x = 12 / 3 = 4"
    },
    {
      "id": 22,
      "topic_id": "linear_eq",
      "question": "Решите уравнение: 7x + 14 = 0",
      "type": "input",
      "answer": "-2",
      "choices": null,
      "hint": "7x = -14 → x = -2",
      "question_uz": "Tenglamani yeching: 7x + 14 = 0",
      "answer_uz": "-2",
      "choices_uz": "",
      "hint_uz": "7x = -14 → x = -2"
    },
    {
      "id": 23,
      "topic_id": "linear_eq",
      "question": "Решите уравнение: 4x - 4 = 12",
      "type": "input",
      "answer": "4",
      "choices": null,
      "hint": "4x = 16 → x = 4",
      "question_uz": "Tenglamani yeching: 4x - 4 = 12",
      "answer_uz": "4",
      "choices_uz": "",
      "hint_uz": "4x = 16 → x = 4"
    }
  ],
  "linear_fn": [
    {
      "id": 54,
      "topic_id": "linear_fn",
      "question": "y = 3x + 2. При x = 4, y = ?",
      "type": "input",
      "answer": "14",
      "choices": null,
      "hint": "y = 3·4 + 2 = 12 + 2 = 14",
      "question_uz": "y = 3x + 2. x = 4 bo‘lganda y = ?",
      "answer_uz": "14",
      "choices_uz": "",
      "hint_uz": "y = 3·4 + 2 = 12 + 2 = 14"
    },
    {
      "id": 55,
      "topic_id": "linear_fn",
      "question": "Угловой коэффициент функции y = -5x + 1 равен:",
      "type": "choice",
      "answer": "-5",
      "choices": [
        "-5",
        "5",
        "1",
        "-1"
      ],
      "hint": "В y = kx + b, k — угловой коэффициент. Здесь k = -5.",
      "question_uz": "y = -5x + 1 funksiyaning burchak koeffitsienti:",
      "answer_uz": "-5",
      "choices_uz": [
        "-5",
        "5",
        "1",
        "-1"
      ],
      "hint_uz": "y = kx + b da k — burchak koeffitsienti. Bu yerda k = -5."
    },
    {
      "id": 56,
      "topic_id": "linear_fn",
      "question": "y = 2x − 3. При каком x значение y = 0?",
      "type": "input",
      "answer": "1.5",
      "choices": null,
      "hint": "0 = 2x - 3 → 2x = 3 → x = 1.5",
      "question_uz": "y = 2x − 3. Qaysi x da y = 0?",
      "answer_uz": "1.5",
      "choices_uz": "",
      "hint_uz": "0 = 2x - 3 → 2x = 3 → x = 1.5"
    },
    {
      "id": 57,
      "topic_id": "linear_fn",
      "question": "Прямая y = kx + b пересекает ось y в точке:",
      "type": "choice",
      "answer": "(0, b)",
      "choices": [
        "(0, b)",
        "(b, 0)",
        "(k, 0)",
        "(0, k)"
      ],
      "hint": "При x=0: y = b. Значит, пересечение с осью y — точка (0, b).",
      "question_uz": "y = kx + b to‘g‘ri chiziq y o‘qini qaysi nuqtada kesadi?",
      "answer_uz": "(0, b)",
      "choices_uz": [
        "(0, b)",
        "(b, 0)",
        "(k, 0)",
        "(0, k)"
      ],
      "hint_uz": "x=0 da y = b. Demak y o‘qi bilan kesishish nuqtasi (0, b)."
    },
    {
      "id": 58,
      "topic_id": "linear_fn",
      "question": "Функция y = 4x + 5. При x = −1, y = ?",
      "type": "input",
      "answer": "1",
      "choices": null,
      "hint": "y = 4·(−1) + 5 = −4 + 5 = 1",
      "question_uz": "Funksiya y = 4x + 5. x = −1 bo‘lganda y = ?",
      "answer_uz": "1",
      "choices_uz": "",
      "hint_uz": "y = 4·(−1) + 5 = −4 + 5 = 1"
    }
  ],
  "nat_numbers": [
    {
      "id": 69,
      "topic_id": "nat_numbers",
      "question": "Какое из чисел является натуральным?",
      "type": "choice",
      "answer": "7",
      "choices": [
        "7",
        "0",
        "-3",
        "1/2"
      ],
      "hint": "Натуральные числа: 1, 2, 3, 4, ... (начинаются с 1, без нуля и отрицательных).",
      "question_uz": "Qaysi son natural son?",
      "answer_uz": "7",
      "choices_uz": [
        "7",
        "0",
        "-3",
        "1/2"
      ],
      "hint_uz": "Natural sonlar: 1, 2, 3, 4, ... (1 dan boshlanadi, 0 va manfiy yo‘q)."
    },
    {
      "id": 70,
      "topic_id": "nat_numbers",
      "question": "Наименьшее натуральное число равно:",
      "type": "input",
      "answer": "1",
      "choices": null,
      "hint": "Натуральный ряд начинается с 1.",
      "question_uz": "Eng kichik natural son teng:",
      "answer_uz": "1",
      "choices_uz": "",
      "hint_uz": "Natural qator 1 dan boshlanadi."
    },
    {
      "id": 71,
      "topic_id": "nat_numbers",
      "question": "Является ли 0 натуральным числом?",
      "type": "choice",
      "answer": "Нет",
      "choices": [
        "Нет",
        "Да",
        "Зависит от задачи",
        "В разных странах по-разному"
      ],
      "hint": "В школьной программе России 0 ∉ ℕ. Натуральные: 1, 2, 3, ...",
      "question_uz": "0 natural sonmi?",
      "answer_uz": "Yo‘q",
      "choices_uz": [
        "Yo‘q",
        "Ha",
        "Vaziyatga bog‘liq",
        "Turli mamlakatlarda farq qiladi"
      ],
      "hint_uz": "O‘quv dasturiga ko‘ra 0 ℕ ga kirmaydi. Natural: 1, 2, 3, ..."
    },
    {
      "id": 72,
      "topic_id": "nat_numbers",
      "question": "Сколько натуральных чисел меньше 5?",
      "type": "choice",
      "answer": "4",
      "choices": [
        "4",
        "5",
        "3",
        "6"
      ],
      "hint": "Натуральные числа меньше 5: 1, 2, 3, 4 — итого 4.",
      "question_uz": "5 dan kichik nechta natural son bor?",
      "answer_uz": "4",
      "choices_uz": [
        "4",
        "5",
        "3",
        "6"
      ],
      "hint_uz": "5 dan kichik natural sonlar: 1, 2, 3, 4 — jami 4."
    },
    {
      "id": 73,
      "topic_id": "nat_numbers",
      "question": "ℕ — это обозначение множества:",
      "type": "choice",
      "answer": "натуральных чисел",
      "choices": [
        "натуральных чисел",
        "целых чисел",
        "рациональных чисел",
        "вещественных чисел"
      ],
      "hint": "ℕ = {1, 2, 3, ...} — натуральные числа.",
      "question_uz": "ℕ — bu qaysi to‘plam belgisi?",
      "answer_uz": "natural sonlar",
      "choices_uz": [
        "natural sonlar",
        "butun sonlar",
        "ratsional sonlar",
        "real sonlar"
      ],
      "hint_uz": "ℕ = {1, 2, 3, ...} — natural sonlar."
    }
  ],
  "parabola": [
    {
      "id": 59,
      "topic_id": "parabola",
      "question": "y = x² − 4x + 3. При x = 1, y = ?",
      "type": "input",
      "answer": "0",
      "choices": null,
      "hint": "y = 1 − 4 + 3 = 0",
      "question_uz": "y = x² − 4x + 3. x = 1 bo‘lganda y = ?",
      "answer_uz": "0",
      "choices_uz": "",
      "hint_uz": "y = 1 − 4 + 3 = 0"
    },
    {
      "id": 60,
      "topic_id": "parabola",
      "question": "Парабола y = ax² + bx + c направлена вниз при:",
      "type": "choice",
      "answer": "a < 0",
      "choices": [
        "a < 0",
        "a > 0",
        "b < 0",
        "c < 0"
      ],
      "hint": "При a > 0 ветви вверх; при a < 0 — вниз.",
      "question_uz": "y = ax² + bx + c параbolasi pastga qarab ochiladi qachon:",
      "answer_uz": "a < 0",
      "choices_uz": [
        "a < 0",
        "a > 0",
        "b < 0",
        "c < 0"
      ],
      "hint_uz": "a > 0 da shoxi tepaga; a < 0 da pastga qarab ochiladi."
    },
    {
      "id": 61,
      "topic_id": "parabola",
      "question": "y = x² − 6x + 5. Найдите x вершины параболы.",
      "type": "input",
      "answer": "3",
      "choices": null,
      "hint": "x₀ = -b/(2a) = 6/2 = 3",
      "question_uz": "y = x² − 6x + 5. Parabola tepasining x koordinatasini toping.",
      "answer_uz": "3",
      "choices_uz": "",
      "hint_uz": "x₀ = -b/(2a) = 6/2 = 3"
    },
    {
      "id": 62,
      "topic_id": "parabola",
      "question": "Вершина параболы y = (x − 3)² + 2 находится в точке:",
      "type": "choice",
      "answer": "(3, 2)",
      "choices": [
        "(3, 2)",
        "(−3, 2)",
        "(3, −2)",
        "(2, 3)"
      ],
      "hint": "В форме y = (x − x₀)² + y₀ вершина сразу: (x₀, y₀) = (3, 2).",
      "question_uz": "y = (x − 3)² + 2 parabola tepasining koordinatasi:",
      "answer_uz": "(3, 2)",
      "choices_uz": [
        "(3, 2)",
        "(−3, 2)",
        "(3, −2)",
        "(2, 3)"
      ],
      "hint_uz": "y = (x − x₀)² + y₀ ko‘rinishida, tepa darhol (x₀, y₀) = (3, 2)."
    },
    {
      "id": 63,
      "topic_id": "parabola",
      "question": "y = 2x² − 8x + 6. При x = 0, y = ?",
      "type": "input",
      "answer": "6",
      "choices": null,
      "hint": "y = 0 − 0 + 6 = 6",
      "question_uz": "y = 2x² − 8x + 6. x = 0 bo‘lganda y = ?",
      "answer_uz": "6",
      "choices_uz": "",
      "hint_uz": "y = 0 − 0 + 6 = 6"
    }
  ],
  "percents": [
    {
      "id": 99,
      "topic_id": "percents",
      "question": "Найдите 20% от числа 150.",
      "type": "input",
      "answer": "30",
      "choices": null,
      "hint": "20% от 150 = 150 · 20 / 100 = 30.",
      "question_uz": "150 sonning 20% ini toping.",
      "answer_uz": "30",
      "choices_uz": "",
      "hint_uz": "150 · 20 / 100 = 30."
    },
    {
      "id": 100,
      "topic_id": "percents",
      "question": "Число 80 — это 40% от какого числа?",
      "type": "input",
      "answer": "200",
      "choices": null,
      "hint": "X = 80 · 100 / 40 = 200.",
      "question_uz": "80 qaysi sonning 40% i?",
      "answer_uz": "200",
      "choices_uz": "",
      "hint_uz": "X = 80 · 100 / 40 = 200."
    },
    {
      "id": 101,
      "topic_id": "percents",
      "question": "Сколько процентов составляет 45 от 180?",
      "type": "input",
      "answer": "25",
      "choices": null,
      "hint": "P = 45 · 100 / 180 = 25%.",
      "question_uz": "180 ning 45 tasi necha foiz?",
      "answer_uz": "25",
      "choices_uz": "",
      "hint_uz": "P = 45 · 100 / 180 = 25%."
    },
    {
      "id": 102,
      "topic_id": "percents",
      "question": "Цена выросла с 500 до 600 руб. На сколько процентов?",
      "type": "input",
      "answer": "20",
      "choices": null,
      "hint": "Рост = 100/500 × 100 = 20%.",
      "question_uz": "Narx 500 dan 600 gacha oshdi. Necha foizga?",
      "answer_uz": "20",
      "choices_uz": "",
      "hint_uz": "O‘sish = 100/500 × 100 = 20%."
    },
    {
      "id": 103,
      "topic_id": "percents",
      "question": "1% = ?",
      "type": "choice",
      "answer": "0.01",
      "choices": [
        "0.01",
        "0.1",
        "1",
        "0.001"
      ],
      "hint": "1% = 1/100 = 0.01.",
      "question_uz": "1% = ?",
      "answer_uz": "0.01",
      "choices_uz": [
        "0.01",
        "0.1",
        "1",
        "0.001"
      ],
      "hint_uz": "1% = 1/100 = 0.01."
    }
  ],
  "quadratic_eq": [
    {
      "id": 3,
      "topic_id": "quadratic_eq",
      "question": "Найди корни уравнения x^2 - 5x + 6 = 0",
      "type": "input",
      "answer": "2,3",
      "choices": null,
      "hint": "D = 25 - 24 = 1  ->  x1 = 3, x2 = 2",
      "question_uz": "",
      "answer_uz": "",
      "choices_uz": "",
      "hint_uz": ""
    },
    {
      "id": 4,
      "topic_id": "quadratic_eq",
      "question": "Дискриминант уравнения x^2 + 2x + 1 = 0 равен?",
      "type": "choice",
      "answer": "0",
      "choices": [
        "4",
        "0",
        "-4",
        "2"
      ],
      "hint": "D = b^2 - 4ac = 4 - 4 = 0",
      "question_uz": "",
      "answer_uz": "",
      "choices_uz": "",
      "hint_uz": ""
    },
    {
      "id": 24,
      "topic_id": "quadratic_eq",
      "question": "Дискриминант уравнения x² - 5x + 6 = 0 равен:",
      "type": "input",
      "answer": "1",
      "choices": null,
      "hint": "D = b² - 4ac = 25 - 24 = 1",
      "question_uz": "x² - 5x + 6 = 0 tenglamaning diskriminanti:",
      "answer_uz": "1",
      "choices_uz": "",
      "hint_uz": "D = b² - 4ac = 25 - 24 = 1"
    },
    {
      "id": 25,
      "topic_id": "quadratic_eq",
      "question": "Уравнение x² - 5x + 6 = 0 имеет корни:",
      "type": "choice",
      "answer": "x=2 и x=3",
      "choices": [
        "x=2 и x=3",
        "x=1 и x=6",
        "x=-2 и x=-3",
        "x=5 и x=1"
      ],
      "hint": "D=1; x=(5±1)/2 → x=3 или x=2",
      "question_uz": "x² - 5x + 6 = 0 tenglamaning ildizlari:",
      "answer_uz": "x=2 и x=3",
      "choices_uz": [
        "x=2 и x=3",
        "x=1 и x=6",
        "x=-2 и x=-3",
        "x=5 и x=1"
      ],
      "hint_uz": "D=1; x=(5±1)/2 → x=3 yoki x=2"
    },
    {
      "id": 26,
      "topic_id": "quadratic_eq",
      "question": "Найдите дискриминант: x² + 4x + 4 = 0",
      "type": "input",
      "answer": "0",
      "choices": null,
      "hint": "D = 16 - 16 = 0 — один корень.",
      "question_uz": "Diskriminantni toping: x² + 4x + 4 = 0",
      "answer_uz": "0",
      "choices_uz": "",
      "hint_uz": "D = 16 - 16 = 0 — bitta ildiz."
    },
    {
      "id": 27,
      "topic_id": "quadratic_eq",
      "question": "При D < 0 квадратное уравнение имеет:",
      "type": "choice",
      "answer": "нет действительных корней",
      "choices": [
        "нет действительных корней",
        "один корень",
        "два корня",
        "бесконечно много"
      ],
      "hint": "Если дискриминант отрицательный — корней в ℝ нет.",
      "question_uz": "D < 0 bo‘lsa kvadrat tenglama qanday ildizlarga ega?",
      "answer_uz": "real ildizlar yo‘q",
      "choices_uz": [
        "real ildizlar yo‘q",
        "bitta ildiz",
        "ikki ildiz",
        "cheksiz ko‘p"
      ],
      "hint_uz": "Agar diskriminant manfiy bo‘lsa, ℝ da ildizlar yo‘q."
    },
    {
      "id": 28,
      "topic_id": "quadratic_eq",
      "question": "Уравнение x² - 9 = 0. Положительный корень x = ?",
      "type": "input",
      "answer": "3",
      "choices": null,
      "hint": "x² = 9 → x = ±3. Положительный: 3.",
      "question_uz": "x² - 9 = 0 tenglama. Musbat ildiz x = ?",
      "answer_uz": "3",
      "choices_uz": "",
      "hint_uz": "x² = 9 → x = ±3. Musbat: 3."
    }
  ],
  "rationals": [
    {
      "id": 79,
      "topic_id": "rationals",
      "question": "Рациональное число — это число вида:",
      "type": "choice",
      "answer": "p/q, где p, q ∈ ℤ, q ≠ 0",
      "choices": [
        "p/q, где p, q ∈ ℤ, q ≠ 0",
        "только целые числа",
        "только дроби",
        "числа с конечным числом знаков"
      ],
      "hint": "ℚ = {p/q | p, q ∈ ℤ, q ≠ 0}.",
      "question_uz": "Ratsional son — bu qanday ko‘rinishdagi son?",
      "answer_uz": "p/q, bu yerda p, q ∈ ℤ, q ≠ 0",
      "choices_uz": [
        "p/q, bu yerda p, q ∈ ℤ, q ≠ 0",
        "faqat butun sonlar",
        "faqat kasrlar",
        "cheklangan raqamli sonlar"
      ],
      "hint_uz": "ℚ = {p/q | p, q ∈ ℤ, q ≠ 0}."
    },
    {
      "id": 80,
      "topic_id": "rationals",
      "question": "Является ли 0.75 рациональным числом?",
      "type": "choice",
      "answer": "Да, это 3/4",
      "choices": [
        "Да, это 3/4",
        "Нет",
        "Только если округлить",
        "Зависит от контекста"
      ],
      "hint": "0.75 = 75/100 = 3/4 — рациональное число.",
      "question_uz": "0.75 ratsional sonmi?",
      "answer_uz": "Ha, bu 3/4",
      "choices_uz": [
        "Ha, bu 3/4",
        "Yo‘q",
        "Faqat yaxlitlasam",
        "Kontextga bog‘liq"
      ],
      "hint_uz": "0.75 = 75/100 = 3/4 — ratsional son."
    },
    {
      "id": 81,
      "topic_id": "rationals",
      "question": "Дробь 1/3 в десятичной записи:",
      "type": "choice",
      "answer": "0.333... (бесконечная периодическая)",
      "choices": [
        "0.333... (бесконечная периодическая)",
        "0.33 (конечная)",
        "3.0",
        "0.3"
      ],
      "hint": "1/3 = 0.(3) — бесконечная периодическая дробь; она всё равно рациональна.",
      "question_uz": "1/3 kasrining o‘nlik yozuvi qanday?",
      "answer_uz": "0.333... (cheksiz davriy)",
      "choices_uz": [
        "0.333... (cheksiz davriy)",
        "0.33 (cheklangan)",
        "3.0",
        "0.3"
      ],
      "hint_uz": "1/3 = 0.(3) — cheksiz davriy kasr; u baribir ratsional."
    },
    {
      "id": 82,
      "topic_id": "rationals",
      "question": "Верно ли: ℤ ⊂ ℚ?",
      "type": "choice",
      "answer": "Да",
      "choices": [
        "Да",
        "Нет",
        "Частично",
        "Только для положительных"
      ],
      "hint": "Любое целое n можно записать как n/1 ∈ ℚ, значит ℤ ⊂ ℚ.",
      "question_uz": "To‘g‘rimi: ℤ ⊂ ℚ?",
      "answer_uz": "Ha",
      "choices_uz": [
        "Ha",
        "Yo‘q",
        "Qisman",
        "Faqat musbatlar uchun"
      ],
      "hint_uz": "Har bir butun n ni n/1 tarzda yozish mumkin, ya’ni ℤ ⊂ ℚ."
    },
    {
      "id": 83,
      "topic_id": "rationals",
      "question": "Упростите дробь: 12/18 = ?/3",
      "type": "input",
      "answer": "2",
      "choices": null,
      "hint": "12/18 = 2/3; в числителе 2.",
      "question_uz": "12/18 kasrini soddalashtiring: ?/3",
      "answer_uz": "2",
      "choices_uz": "",
      "hint_uz": "12/18 = 2/3; chislovchi 2."
    }
  ],
  "reals": [
    {
      "id": 89,
      "topic_id": "reals",
      "question": "Множество вещественных чисел ℝ включает:",
      "type": "choice",
      "answer": "ℚ и иррациональные числа",
      "choices": [
        "ℚ и иррациональные числа",
        "только рациональные",
        "только иррациональные",
        "комплексные числа"
      ],
      "hint": "ℝ = ℚ ∪ (иррациональные). Каждой точке на числовой прямой соответствует вещественное число.",
      "question_uz": "ℝ haqiqiy sonlar to‘plamiga nimalar kiradi?",
      "answer_uz": "ℚ va irratsional sonlar",
      "choices_uz": [
        "ℚ va irratsional sonlar",
        "faqat ratsional",
        "faqat irratsional",
        "kompleks sonlar"
      ],
      "hint_uz": "ℝ = ℚ ∪ (irratsional). Har bir nuqta haqiqiy son bilan mos keladi."
    },
    {
      "id": 90,
      "topic_id": "reals",
      "question": "Верно ли: ℚ ⊂ ℝ?",
      "type": "choice",
      "answer": "Да",
      "choices": [
        "Да",
        "Нет",
        "Только для положительных",
        "Только для целых"
      ],
      "hint": "Рациональные числа — подмножество вещественных: ℚ ⊂ ℝ.",
      "question_uz": "To‘g‘rimi: ℚ ⊂ ℝ?",
      "answer_uz": "Ha",
      "choices_uz": [
        "Ha",
        "Yo‘q",
        "Faqat musbatlar uchun",
        "Faqat butunlar uchun"
      ],
      "hint_uz": "Ratsional sonlar haqiqiy sonlar ichida: ℚ ⊂ ℝ."
    },
    {
      "id": 91,
      "topic_id": "reals",
      "question": "Каждой точке числовой прямой соответствует:",
      "type": "choice",
      "answer": "вещественное число",
      "choices": [
        "вещественное число",
        "рациональное число",
        "натуральное число",
        "комплексное число"
      ],
      "hint": "Числовая прямая — геометрическая модель множества ℝ.",
      "question_uz": "Raqamlar chizig‘idagi har bir nuqtaga nima mos keladi?",
      "answer_uz": "haqiqiy son",
      "choices_uz": [
        "haqiqiy son",
        "ratsional son",
        "natural son",
        "kompleks son"
      ],
      "hint_uz": "Raqamlar chizig‘i ℝ to‘plamining geometrik modeli."
    },
    {
      "id": 92,
      "topic_id": "reals",
      "question": "Правильный порядок вложенности множеств:",
      "type": "choice",
      "answer": "ℕ ⊂ ℤ ⊂ ℚ ⊂ ℝ",
      "choices": [
        "ℕ ⊂ ℤ ⊂ ℚ ⊂ ℝ",
        "ℤ ⊂ ℕ ⊂ ℚ ⊂ ℝ",
        "ℝ ⊂ ℚ ⊂ ℤ ⊂ ℕ",
        "ℕ ⊂ ℚ ⊂ ℤ ⊂ ℝ"
      ],
      "hint": "Каждое следующее множество шире предыдущего: ℕ ⊂ ℤ ⊂ ℚ ⊂ ℝ.",
      "question_uz": "To‘g‘ri to‘plamlar o‘zaro joylashuvi tartibi:",
      "answer_uz": "ℕ ⊂ ℤ ⊂ ℚ ⊂ ℝ",
      "choices_uz": [
        "ℕ ⊂ ℤ ⊂ ℚ ⊂ ℝ",
        "ℤ ⊂ ℕ ⊂ ℚ ⊂ ℝ",
        "ℝ ⊂ ℚ ⊂ ℤ ⊂ ℕ",
        "ℕ ⊂ ℚ ⊂ ℤ ⊂ ℝ"
      ],
      "hint_uz": "Har bir keyingi to‘plam oldingisidan kengroq: ℕ ⊂ ℤ ⊂ ℚ ⊂ ℝ."
    },
    {
      "id": 93,
      "topic_id": "reals",
      "question": "Число √(-1) является вещественным числом?",
      "type": "choice",
      "answer": "Нет",
      "choices": [
        "Нет",
        "Да",
        "Только в особых случаях",
        "Зависит от определения"
      ],
      "hint": "Квадратный корень из отрицательного числа не является вещественным — это мнимая единица i.",
      "question_uz": "√(-1) soni haqiqiy sonmi?",
      "answer_uz": "Yo‘q",
      "choices_uz": [
        "Yo‘q",
        "Ha",
        "Faqat alohida holatlarda",
        "Ta’rifga bog‘liq"
      ],
      "hint_uz": "Manfiy sonning kvadrat ildizi haqiqiy emas — bu i tasodifiy birlik."
    }
  ],
  "right_triangle": [
    {
      "id": 1,
      "topic_id": "right_triangle",
      "question": "Катеты треугольника a = 3, b = 4. Найди гипотенузу c.",
      "type": "input",
      "answer": "5",
      "choices": null,
      "hint": "a^2 + b^2 = c^2  ->  9 + 16 = 25  ->  c = 5",
      "question_uz": "",
      "answer_uz": "",
      "choices_uz": "",
      "hint_uz": ""
    },
    {
      "id": 2,
      "topic_id": "right_triangle",
      "question": "Чему равен sin a, если противолежащий катет = 3, гипотенуза = 5?",
      "type": "choice",
      "answer": "0.6",
      "choices": [
        "0.8",
        "0.6",
        "0.75",
        "1.67"
      ],
      "hint": "sin a = противолежащий катет / гипотенуза = 3/5 = 0.6",
      "question_uz": "",
      "answer_uz": "",
      "choices_uz": "",
      "hint_uz": ""
    },
    {
      "id": 9,
      "topic_id": "right_triangle",
      "question": "Катеты прямоугольного треугольника равны 3 и 4. Найдите гипотенузу.",
      "type": "input",
      "answer": "5",
      "choices": null,
      "hint": "c = √(a² + b²) = √(9 + 16) = √25 = 5",
      "question_uz": "Toʻgʻri burchakli uchburchakning katetlari 3 va 4. Gipotenuzani toping.",
      "answer_uz": "5",
      "choices_uz": "",
      "hint_uz": "c = √(a² + b²) = √(9 + 16) = √25 = 5"
    },
    {
      "id": 10,
      "topic_id": "right_triangle",
      "question": "Гипотенуза = 13, один катет = 5. Найдите второй катет.",
      "type": "input",
      "answer": "12",
      "choices": null,
      "hint": "b = √(c² - a²) = √(169 - 25) = √144 = 12",
      "question_uz": "Gipotenuza 13, bir katet 5. Ikkinchi katetni toping.",
      "answer_uz": "12",
      "choices_uz": "",
      "hint_uz": "b = √(c² - a²) = √(169 - 25) = √144 = 12"
    },
    {
      "id": 11,
      "topic_id": "right_triangle",
      "question": "Чему равно sin 30°?",
      "type": "choice",
      "answer": "0.5",
      "choices": [
        "0.5",
        "√3/2",
        "1",
        "0"
      ],
      "hint": "sin 30° = 1/2 = 0.5 — одно из базовых значений.",
      "question_uz": "sin 30° qancha?",
      "answer_uz": "0.5",
      "choices_uz": [
        "0.5",
        "√3/2",
        "1",
        "0"
      ],
      "hint_uz": "sin 30° = 1/2 = 0.5 — asosiy qiymatlardan biri."
    },
    {
      "id": 12,
      "topic_id": "right_triangle",
      "question": "В прямоугольном треугольнике катеты 6 и 8. Площадь = ?",
      "type": "input",
      "answer": "24",
      "choices": null,
      "hint": "S = a·b/2 = 6·8/2 = 24",
      "question_uz": "Toʻgʻri burchakli uchburchakda katetlar 6 va 8. Yuzani toping.",
      "answer_uz": "24",
      "choices_uz": "",
      "hint_uz": "S = a·b/2 = 6·8/2 = 24"
    },
    {
      "id": 13,
      "topic_id": "right_triangle",
      "question": "Сумма двух острых углов прямоугольного треугольника равна:",
      "type": "choice",
      "answer": "90°",
      "choices": [
        "90°",
        "180°",
        "45°",
        "60°"
      ],
      "hint": "Сумма всех углов = 180°; прямой угол = 90°; значит α + β = 90°.",
      "question_uz": "Toʻgʻri burchakli uchburchakning ikkita o'tkir burchagi yigʻindisi teng:",
      "answer_uz": "90°",
      "choices_uz": [
        "90°",
        "180°",
        "45°",
        "60°"
      ],
      "hint_uz": "Barcha burchaklar yigʻindisi 180°; toʻgʻri burchak 90°; demak α + β = 90°."
    }
  ],
  "sin_cos_theorems": [
    {
      "id": 49,
      "topic_id": "sin_cos_theorems",
      "question": "Теорема косинусов: c² = ?",
      "type": "choice",
      "answer": "a² + b² - 2ab·cosC",
      "choices": [
        "a² + b² - 2ab·cosC",
        "a² + b²",
        "a² - b² + 2ab·cosC",
        "2ab·cosC"
      ],
      "hint": "Теорема косинусов обобщает теорему Пифагора: c² = a² + b² - 2ab·cosC.",
      "question_uz": "Kosinuslar teoremasi: c² = ?",
      "answer_uz": "a² + b² - 2ab·cosC",
      "choices_uz": [
        "a² + b² - 2ab·cosC",
        "a² + b²",
        "a² - b² + 2ab·cosC",
        "2ab·cosC"
      ],
      "hint_uz": "Kosinuslar teoremasi Pifagor teoremasining umumlashmasi: c² = a² + b² - 2ab·cosC."
    },
    {
      "id": 50,
      "topic_id": "sin_cos_theorems",
      "question": "Теорема синусов: a/sinA = ?",
      "type": "choice",
      "answer": "2R",
      "choices": [
        "2R",
        "R",
        "R/2",
        "πR"
      ],
      "hint": "a/sinA = b/sinB = c/sinC = 2R, где R — радиус описанной окружности.",
      "question_uz": "Sinuslar teoremasi: a/sinA = ?",
      "answer_uz": "2R",
      "choices_uz": [
        "2R",
        "R",
        "R/2",
        "πR"
      ],
      "hint_uz": "a/sinA = b/sinB = c/sinC = 2R, bu yerda R — tashqi aylananing radiusi."
    },
    {
      "id": 51,
      "topic_id": "sin_cos_theorems",
      "question": "В треугольнике c = 10, C = 90°. По теореме синусов 2R = ?",
      "type": "choice",
      "answer": "10",
      "choices": [
        "10",
        "5",
        "20",
        "100"
      ],
      "hint": "c/sinC = 10/sin90° = 10/1 = 10 = 2R.",
      "question_uz": "Uchburchakda c = 10, C = 90°. Sinuslar teoremasiga ko‘ra 2R = ?",
      "answer_uz": "10",
      "choices_uz": [
        "10",
        "5",
        "20",
        "100"
      ],
      "hint_uz": "c/sinC = 10/sin90° = 10/1 = 10 = 2R."
    },
    {
      "id": 52,
      "topic_id": "sin_cos_theorems",
      "question": "Треугольник: a=7, b=7, C=60°. По теореме косинусов c² = ?",
      "type": "input",
      "answer": "49",
      "choices": null,
      "hint": "c² = 49 + 49 - 2·7·7·cos60° = 98 - 98·0.5 = 98 - 49 = 49",
      "question_uz": "Uchburchak: a=7, b=7, C=60°. Kosinuslar teoremasiga ko‘ra c² = ?",
      "answer_uz": "49",
      "choices_uz": "",
      "hint_uz": "c² = 49 + 49 - 2·7·7·cos60° = 98 - 98·0.5 = 98 - 49 = 49"
    },
    {
      "id": 53,
      "topic_id": "sin_cos_theorems",
      "question": "При каком условии теорема косинусов превращается в теорему Пифагора?",
      "type": "choice",
      "answer": "C = 90°",
      "choices": [
        "C = 90°",
        "C = 0°",
        "A = B",
        "c = R"
      ],
      "hint": "cos90° = 0, поэтому c² = a² + b² - 0 = a² + b².",
      "question_uz": "Qaysi shartda kosinuslar teoremasi Pifagor teoremasiga aylanadi?",
      "answer_uz": "C = 90°",
      "choices_uz": [
        "C = 90°",
        "C = 0°",
        "A = B",
        "c = R"
      ],
      "hint_uz": "cos90° = 0, shuning uchun c² = a² + b² - 0 = a² + b²."
    }
  ],
  "trig_formulas": [
    {
      "id": 39,
      "topic_id": "trig_formulas",
      "question": "Основное тригонометрическое тождество:",
      "type": "choice",
      "answer": "sin²α + cos²α = 1",
      "choices": [
        "sin²α + cos²α = 1",
        "sinα · cosα = 1",
        "sin²α = cos²α",
        "tgα = sinα + cosα"
      ],
      "hint": "Из теоремы Пифагора на единичной окружности: sin²α + cos²α = 1.",
      "question_uz": "Asosiy trigonometrik tenglik:",
      "answer_uz": "sin²α + cos²α = 1",
      "choices_uz": [
        "sin²α + cos²α = 1",
        "sinα · cosα = 1",
        "sin²α = cos²α",
        "tgα = sinα + cosα"
      ],
      "hint_uz": "Yagona aylanada Pifagor teoremasidan: sin²α + cos²α = 1."
    },
    {
      "id": 40,
      "topic_id": "trig_formulas",
      "question": "tg α = ?",
      "type": "choice",
      "answer": "sinα / cosα",
      "choices": [
        "sinα / cosα",
        "cosα / sinα",
        "sinα · cosα",
        "1 / sinα"
      ],
      "hint": "tg α = sinα / cosα (тангенс — отношение синуса к косинусу).",
      "question_uz": "tg α = ?",
      "answer_uz": "sinα / cosα",
      "choices_uz": [
        "sinα / cosα",
        "cosα / sinα",
        "sinα · cosα",
        "1 / sinα"
      ],
      "hint_uz": "tg α = sinα / cosα (tangent — sin va cos nisbatidir)."
    },
    {
      "id": 41,
      "topic_id": "trig_formulas",
      "question": "Если sinα = 0.6, найдите cosα (α — острый угол). Ответ округлите до 1 знака.",
      "type": "input",
      "answer": "0.8",
      "choices": null,
      "hint": "cos²α = 1 - sin²α = 1 - 0.36 = 0.64 → cosα = 0.8",
      "question_uz": "Agar sinα = 0.6 bo‘lsa, cosα ni toping (α — o'tkir burchak). Javobni 1 xonagacha yaxlitlang.",
      "answer_uz": "0.8",
      "choices_uz": "",
      "hint_uz": "cos²α = 1 - sin²α = 1 - 0.36 = 0.64 → cosα = 0.8"
    },
    {
      "id": 42,
      "topic_id": "trig_formulas",
      "question": "sin(α + β) = ?",
      "type": "choice",
      "answer": "sinα·cosβ + cosα·sinβ",
      "choices": [
        "sinα·cosβ + cosα·sinβ",
        "sinα + sinβ",
        "sinα·sinβ + cosα·cosβ",
        "sinα·cosβ - cosα·sinβ"
      ],
      "hint": "Формула сложения: sin(α + β) = sinα·cosβ + cosα·sinβ.",
      "question_uz": "sin(α + β) = ?",
      "answer_uz": "sinα·cosβ + cosα·sinβ",
      "choices_uz": [
        "sinα·cosβ + cosα·sinβ",
        "sinα + sinβ",
        "sinα·sinβ + cosα·cosβ",
        "sinα·cosβ - cosα·sinβ"
      ],
      "hint_uz": "Yig‘indi formulası: sin(α + β) = sinα·cosβ + cosα·sinβ."
    },
    {
      "id": 43,
      "topic_id": "trig_formulas",
      "question": "ctg α = ?",
      "type": "choice",
      "answer": "cosα / sinα",
      "choices": [
        "cosα / sinα",
        "sinα / cosα",
        "1 / cosα",
        "cosα · sinα"
      ],
      "hint": "ctg — котангенс: ctg α = cosα / sinα = 1 / tg α.",
      "question_uz": "ctg α = ?",
      "answer_uz": "cosα / sinα",
      "choices_uz": [
        "cosα / sinα",
        "sinα / cosα",
        "1 / cosα",
        "cosα · sinα"
      ],
      "hint_uz": "ctg — kotangens: ctg α = cosα / sinα = 1 / tg α."
    }
  ],
  "trig_values": [
    {
      "id": 34,
      "topic_id": "trig_values",
      "question": "sin 30° = ?",
      "type": "choice",
      "answer": "1/2",
      "choices": [
        "1/2",
        "√2/2",
        "√3/2",
        "1"
      ],
      "hint": "sin 30° = 0.5 = 1/2 — стандартное значение.",
      "question_uz": "sin 30° = ?",
      "answer_uz": "1/2",
      "choices_uz": [
        "1/2",
        "√2/2",
        "√3/2",
        "1"
      ],
      "hint_uz": "sin 30° = 0.5 = 1/2 — standart qiymat."
    },
    {
      "id": 35,
      "topic_id": "trig_values",
      "question": "cos 60° = ?",
      "type": "choice",
      "answer": "1/2",
      "choices": [
        "1/2",
        "√3/2",
        "√2/2",
        "0"
      ],
      "hint": "cos 60° = 1/2 — то же значение, что sin 30°.",
      "question_uz": "cos 60° = ?",
      "answer_uz": "1/2",
      "choices_uz": [
        "1/2",
        "√3/2",
        "√2/2",
        "0"
      ],
      "hint_uz": "cos 60° = 1/2 — sin 30° bilan bir xil qiymat."
    },
    {
      "id": 36,
      "topic_id": "trig_values",
      "question": "sin 45° = ?",
      "type": "choice",
      "answer": "√2/2",
      "choices": [
        "√2/2",
        "1/2",
        "√3/2",
        "1"
      ],
      "hint": "sin 45° = cos 45° = √2/2 ≈ 0.707",
      "question_uz": "sin 45° = ?",
      "answer_uz": "√2/2",
      "choices_uz": [
        "√2/2",
        "1/2",
        "√3/2",
        "1"
      ],
      "hint_uz": "sin 45° = cos 45° = √2/2 ≈ 0.707"
    },
    {
      "id": 37,
      "topic_id": "trig_values",
      "question": "cos 0° = ?",
      "type": "choice",
      "answer": "1",
      "choices": [
        "1",
        "0",
        "1/2",
        "√2/2"
      ],
      "hint": "При угле 0° точка на единичной окружности: (1, 0) → cos 0° = 1.",
      "question_uz": "cos 0° = ?",
      "answer_uz": "1",
      "choices_uz": [
        "1",
        "0",
        "1/2",
        "√2/2"
      ],
      "hint_uz": "0° burchakda birlik aylana nuqtasi: (1,0) → cos 0° = 1."
    },
    {
      "id": 38,
      "topic_id": "trig_values",
      "question": "sin 90° = ?",
      "type": "choice",
      "answer": "1",
      "choices": [
        "1",
        "0",
        "1/2",
        "√3/2"
      ],
      "hint": "При 90° точка (0, 1) → sin 90° = 1.",
      "question_uz": "sin 90° = ?",
      "answer_uz": "1",
      "choices_uz": [
        "1",
        "0",
        "1/2",
        "√3/2"
      ],
      "hint_uz": "90° da nuqta (0,1) → sin 90° = 1."
    }
  ],
  "unit_circle": [
    {
      "id": 44,
      "topic_id": "unit_circle",
      "question": "Радиус единичной окружности равен:",
      "type": "choice",
      "answer": "1",
      "choices": [
        "1",
        "2",
        "π",
        "360"
      ],
      "hint": "Единичная окружность — окружность с центром в O и радиусом 1.",
      "question_uz": "Yagona aylananing radiusi teng:",
      "answer_uz": "1",
      "choices_uz": [
        "1",
        "2",
        "π",
        "360"
      ],
      "hint_uz": "Yagona aylana — markazi O va radiusi 1 bo‘lgan aylana."
    },
    {
      "id": 45,
      "topic_id": "unit_circle",
      "question": "Координата точки на единичной окружности при угле α: (x, y) = ?",
      "type": "choice",
      "answer": "(cosα, sinα)",
      "choices": [
        "(cosα, sinα)",
        "(sinα, cosα)",
        "(α, α)",
        "(tgα, 1)"
      ],
      "hint": "На единичной окружности: x = cosα, y = sinα.",
      "question_uz": "Yagona aylanadagi nuqtaning koordinatasi α burchakda: (x, y) = ?",
      "answer_uz": "(cosα, sinα)",
      "choices_uz": [
        "(cosα, sinα)",
        "(sinα, cosα)",
        "(α, α)",
        "(tgα, 1)"
      ],
      "hint_uz": "Yagona aylanada: x = cosα, y = sinα."
    },
    {
      "id": 46,
      "topic_id": "unit_circle",
      "question": "Угол 180° в радианах равен:",
      "type": "choice",
      "answer": "π",
      "choices": [
        "π",
        "2π",
        "π/2",
        "π/4"
      ],
      "hint": "180° = π радиан. Полный оборот 360° = 2π.",
      "question_uz": "180° burchak radianlarda teng:",
      "answer_uz": "π",
      "choices_uz": [
        "π",
        "2π",
        "π/2",
        "π/4"
      ],
      "hint_uz": "180° = π radian. To‘liq aylanish 360° = 2π."
    },
    {
      "id": 47,
      "topic_id": "unit_circle",
      "question": "Угол 90° в радианах равен:",
      "type": "choice",
      "answer": "π/2",
      "choices": [
        "π/2",
        "π",
        "π/4",
        "2π"
      ],
      "hint": "90° = π/2 радиана.",
      "question_uz": "90° burchak radianlarda teng:",
      "answer_uz": "π/2",
      "choices_uz": [
        "π/2",
        "π",
        "π/4",
        "2π"
      ],
      "hint_uz": "90° = π/2 radian."
    },
    {
      "id": 48,
      "topic_id": "unit_circle",
      "question": "В каком квадранте синус отрицателен?",
      "type": "choice",
      "answer": "III и IV",
      "choices": [
        "III и IV",
        "I и II",
        "II и III",
        "I и IV"
      ],
      "hint": "sinα = y-координата. Ниже оси x (III и IV квадранты) y < 0.",
      "question_uz": "Qaysi kvadrantda sinus manfiy?",
      "answer_uz": "III и IV",
      "choices_uz": [
        "III и IV",
        "I и II",
        "II и III",
        "I и IV"
      ],
      "hint_uz": "sinα = y koordinatasi. x o‘qidan pastda (III va IV kvadrantlar) y < 0."
    }
  ]
};
